language: node_js
node_js:
 - "0.10"
before_install:
 - gem install sass
script:
 - npm test

env:
  global:
   - GH_REF: "github.com/ertrzyiks/terra-mystica-lobby"
   - GIT_NAME: "ertrzyiks"
   - GIT_EMAIL: "mateusz.derks+travis@gmail.com"
cache:
  directories:
    - node_modules
