language: node_js
node_js:
- "0.10"
before_install:
 - gem install sass
script:
- npm run build
- npm test
cache:
  directories:
    - node_modules
    - bower_components
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: Semmz7jhXzTZ9w4+d++v5Ju4AOIyNuoVHqw+PUES1/QemW6lScNn7VlDy34yD5Q+owSYNyvoclTYKKMoVqeNNrJw3wrUlxuMDCklanNI34rLLh/zFas6afZwSjT49UowAQhZbEhQmjk6vSPRkoJJj1NI5IZiKoxs53M4nogKu9U=
  app: terra-mystica-lobby
  on:
    repo: ertrzyiks/terra-mystica-lobby
